### ISSUE TITLE
Application crashes when generating codes

### ISSUE THREAD

**Issue by eduseiti** [learningtitans/paperclickers#4]
Using Android 6.0 application crashes when generating codes.

ava.lang.IllegalStateException: Underflow in restore - more restores than saves
    at android.graphics.Canvas.native_restore(Native Method)
    at android.graphics.Canvas.restore(Canvas.java:540)
    at com.paperclickers.SettingsActivity.printCodes2PerPage(SettingsActivity.java:582)
    at com.paperclickers.SettingsActivity.printAndShareCodes(SettingsActivity.java:441)
    at com.paperclickers.SettingsActivity.onNewIntent(SettingsActivity.java:299)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1235)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1247)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2563)
    at android.app.ActivityThread.performNewIntents(ActivityThread.java:2575)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2584)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5443)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by eduseiti** [comment]
Problem on SettingsActivity.printCodes2PerPage() method: there were unneeded calls to canvas.restore(); fix will be available on 1.0.2 version.
